metadatastore:
    module: databroker.headersource.mongo
    class: MDS
    config:
        host: 'localhost'
        port: 27017
        database: 'rsoxs-metadata-store'
        timezone: 'US/Eastern'
assets:
    module: databroker.assets.mongo
    class: Registry
    config:
        host: 'localhost'
        port: 27017
        database: 'rsoxs-assets-store'
transforms:
    descriptor: 'nslsii.transforms.rsoxs_fix_shape'
